---
- name: install software
  apt: pkg={{item}} state=installed
  with_items:
    - mc
    - ntp
    - git
    - curl
  notify:
    - restart ntp

- name: install ncurses
  apt: pkg=ncurses-dev state=installed